### ISSUE TITLE
App suggestion: Joplin (notes)

### ISSUE THREAD

**Issue by dabreese00** [offa/android-foss#151]
Would you be willing to consider this suggestion for the Notes section?  Great list by the way, thank you!

MIT license note taking app for Android/iOS/Desktop: https://joplinapp.org/

**Comment by offa** [comment]
Thanks! :smile: 

There's an ongoing discussion regarding F-Droid packing already (https://github.com/laurent22/joplin/issues/15, [rfp](https://gitlab.com/fdroid/rfp/-/issues/434)). It brought up proprietary components incl. firebase – and there's no fully FOSS flavour yet.

But since there's still progress on a FOSS version, maybe we can reconsider it at a later point?

**Comment by dabreese00** [comment]
Oh, good catch!  Glad that you found this thread, I didn't even realize that Joplin had these non-free dependencies.  Yes, fingers crossed for someday in the future...

**Comment by offa** [comment]
It's on F-Droid now! #205
