### ISSUE TITLE
Godot

### ISSUE THREAD

**Issue by RustoMCSpit** [offa/android-foss#291]
https://godotengine.org/download/android/

**Comment by shuvashish76** [comment]
https://www.f-droid.org/en/packages/org.godotengine.editor.v3/
https://www.f-droid.org/en/packages/org.godotengine.editor.v4/

> _The Android editor is currently in an experimental stage. The UI has not been adapted
for touch screens yet; using a hardware keyboard and mouse is strongly recommended._

I didn't add that to list because of this reason but feel free to contribute if you think v4 or v3 stable enough for a normal user.

**Comment by offa** [comment]
Indeed, the notice is placed everywhere. It mentions the editor only though, but the project itself is a game engine (= the actual important stuff!?). Does anyone have more insight here?
