### ISSUE TITLE
What is the point of this list?

### ISSUE THREAD

**Issue by Thestroyer** [offa/android-foss#365]
Well, as no one asked that yet, I would like to discuss, why do we even create and update this list?
As there is already F-droid list of apps and this list in most cases just mentions F-droid apps, what is the point of that? I don't mean that it's bad or sth, but it feels weird, that you find an app on F-droid, then add it to list on github with just link to F-droid.
As F-droid has some troubles now, maybe we should just update their lists and contribute there? So they could focus on technical stuff as compiling etc.

**Comment by offa** [comment]
> Well, as no one asked that yet, I would like to discuss, why do we even create and update this list?

It started as a reminder and way to share an app list with others … and then somehow exploded :boom: :smile:.

 The difference to F-Droids app listing is, that this one gives an overview at a glance. It includes project not available on F-Droid too.

> As F-droid has some troubles now, maybe we should just update their lists and contribute there?

Some contributor – myself included – do this already. :+1:

**Comment by Thestroyer** [comment]
Hmm, yeah but there are really few apps only..maybe this list should have some summary at the beginning? New users just don't know what they should expect by installing programs listed here. Especially if an app is not on f-droid.

**Comment by offa** [comment]
There's one already:

> A list of Free and Open Source Software (FOSS) for Android 

And for those who want to dig deeper, there's a list of [criteria](https://github.com/offa/android-foss/blob/master/CONTRIBUTING.md#criteria).

Giving a detailed insight what they should expect by installation of a listed project is out of scope and might not even be possible.

**Comment by shuvashish76** [comment]
1. F-Droid has a small list of [official categories](https://gitlab.com/fdroid/fdroiddata/blob/master/stats/categories.txt).
2. [Izzy adds few more](https://github.com/offa/android-foss/issues/302#issuecomment-1688876074) to his list.
3. Here we add few more _more_ granular lists :)

> As F-droid has some troubles now, maybe we should just update their lists and contribute there?

Feel free to discuss on [F-Droid data](https://gitlab.com/fdroid/fdroiddata/-/issues) ot their [forum](https://forum.f-droid.org/)

> maybe this list should have some summary at the beginning?

There are many similar projects e.g https://github.com/Psyhackological/AAA, https://github.com/albertomosconi/foss-apps, https://github.com/Divested-Mobile/FOSS_Apps_List, https://github.com/nyas1/Material-You-app-list, https://github.com/ThePBone/awesome-shizuku, https://github.com/Lissy93/awesome-privacy (android mixed) etc... They've descriptions, last commit, version, starts, app icon, Play-store availability, alternative to which proprietary app & may other infos.
I understand these infos can be useful to users but updating/removing them regularly is painful & not possible; though some of the infos can be automated e.g. version, last commit, stars tracking etc.. Feel free to discuss that in #148 if you're willing to do that efficiently no matter where the project is hosted (GitHub, GitLab, Codeberg etc..)

Despite having minimal infos, this project has it's popularity because I guess 1. Easier to update the list 2. Updated more frequently than others
